### ISSUE TITLE
FileNotFoundError: No such file: '/data01/home/scy0764/AD-NeRF-master/AD-NeRF-master/dataset/Obama/bc.jpg'

### ISSUE THREAD

**Issue by smallwhite-dragon** [YudongGuo/AD-NeRF#109]
Traceback (most recent call last):
  File "NeRFs/HeadNeRF/run_nerf.py", line 965, in <module>
    train()
  File "NeRFs/HeadNeRF/run_nerf.py", line 655, in train
    args.datadir, args.testskip)
  File "/data01/home/scy0764/AD-NeRF-master/AD-NeRF-master/NeRFs/HeadNeRF/load_audface.py", line 75, in load_audface_data
    bc_img = imageio.imread(os.path.join(basedir, 'bc.jpg'))
  File "/data01/home/scy0764/.conda/envs/adnerf/lib/python3.7/site-packages/imageio/core/functions.py", line 265, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/data01/home/scy0764/.conda/envs/adnerf/lib/python3.7/site-packages/imageio/core/functions.py", line 172, in get_reader
    request = Request(uri, "r" + mode, **kwargs)
  File "/data01/home/scy0764/.conda/envs/adnerf/lib/python3.7/site-packages/imageio/core/request.py", line 124, in __init__
    self._parse_uri(uri)
  File "/data01/home/scy0764/.conda/envs/adnerf/lib/python3.7/site-packages/imageio/core/request.py", line 260, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: '/data01/home/scy0764/AD-NeRF-master/AD-NeRF-master/dataset/Obama/bc.jpg'

**Comment by zjy-2020** [comment]
Hello, did you solve this problem? I encountered the same issue.
