### ISSUE TITLE
ValueError: Got non-broadcastable sizes [1, 1, 1, 1, 0, 0], c = tensor([], device='cuda:0', size=(0, 3, 3))

### ISSUE THREAD

**Issue by Hybrogen** [YudongGuo/AD-NeRF#122]
当我运行 step 6 的时候出现了这个错误：
```sh
Traceback (most recent call last):
  File "D:\HWork\NEW08\AD-NeRF\data_util\face_tracking\face_tracker.py", line 188, in <module>
    renderer = Render_3DMM(arg_focal, h, w, batch_size, device_render)
  File "D:\HWork\NEW08\AD-NeRF\data_util\face_tracking\render_3dmm.py", line 88, in __init__
    self.renderer = self.get_render(batch_size)
  File "D:\HWork\NEW08\AD-NeRF\data_util\face_tracking\render_3dmm.py", line 113, in get_render
    cameras = FoVPerspectiveCameras(device=self.device, R=R, T=T, znear=0.01, zfar=20,
  File "D:\HPrograms\H_OnInstall\Python\Python310\lib\site-packages\pytorch3d-0.7.4-py3.10-win-amd64.egg\pytorch3d\renderer\cameras.py", line 574, in __init__
    super().__init__(
  File "D:\HPrograms\H_OnInstall\Python\Python310\lib\site-packages\pytorch3d-0.7.4-py3.10-win-amd64.egg\pytorch3d\renderer\utils.py", line 134, in __init__
    broadcasted_values = convert_to_tensors_and_broadcast(
  File "D:\HPrograms\H_OnInstall\Python\Python310\lib\site-packages\pytorch3d-0.7.4-py3.10-win-amd64.egg\pytorch3d\renderer\utils.py", line 350, in convert_to_tensors_and_broadcast
    raise ValueError(msg)
ValueError: Got non-broadcastable sizes [1, 1, 1, 1, 0, 0], c = tensor([], device='cuda:0', size=(0, 3, 3))
```
奇怪的是前一天训练模型的时候还没有出现这个问题，所有流程都跑通了，今天尝试训练自己的模型时出现了这个问题，重新训练 Obama 时也出现了相同的问题，因此感到很困惑。

**Comment by Hybrogen** [comment]
追根溯源，翻了两天源码终于发现第一个参数是前面的 batch_size，默认是 50，网上有文章说内存小可以设成 10，可是我设成 10 电脑还是运行一半自动关机，然后索性设成 0，主要之前搞 wav2lip 的一个参数就可以设成 0 来着，就试试看结果跑不动了，设成 1 出现了另一个报错：
```sh
Traceback (most recent call last):
  File "D:\HWork\NEW08\AD-NeRF\data_util\face_tracking\face_tracker.py", line 326, in <module>
    loss_lap = cal_lap_loss([rott_geo_lap.reshape(rott_geo_lap.shape[0], -1).permute(1, 0)],
  File "D:\HWork\NEW08\AD-NeRF\data_util\face_tracking\util.py", line 55, in cal_lap_loss
    out_tensor = F.conv1d(in_tensor, lap_kernel)
RuntimeError: Calculated padded input size per channel: (1). Kernel size: (3). Kernel size can't be greater than actual input size
```
好在知道自己就改了这一个地方，所以第一时间怀疑是不是还是这里，所以改成 10 果然能跑了。
