### ISSUE TITLE
step 2, error

### ISSUE THREAD

**Issue by mohican521** [YudongGuo/AD-NeRF#130]
Traceback (most recent call last):
  File "data_util/process_data.py", line 95, in <module>
    face_alignment.LandmarksType._2D, flip_input=False)
  File "/opt/conda/lib/python3.8/enum.py", line 346, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D
Traceback (most recent call last):
  File "data_util/process_data.py", line 110, in <module>
Traceback (most recent call last):
  File "data_util/process_data.py", line 110, in <module>
    tmp_img = cv2.imread(os.path.join(ori_imgs_dir, str(valid_img_ids[0])+'.jpg'))
IndexError: list index out of range
    tmp_img = cv2.imread(os.path.join(ori_imgs_dir, str(valid_img_ids[0])+'.jpg'))
IndexError: list index out of range
Traceback (most recent call last):
  File "data_util/process_data.py", line 110, in <module>
    tmp_img = cv2.imread(os.path.join(ori_imgs_dir, str(valid_img_ids[0])+'.jpg'))
IndexError: list index out of range
Traceback (most recent call last):
  File "data_util/process_data.py", line 110, in <module>
    tmp_img = cv2.imread(os.path.join(ori_imgs_dir, str(valid_img_ids[0])+'.jpg'))
IndexError: list index out of range

**Comment by Bertram168** [comment]
hello, I meet the same problem, too. Have you figured out?
