### ISSUE TITLE
detect lands & estimate head pose

### ISSUE THREAD

**Issue by shahriarshakil0** [YudongGuo/AD-NeRF#19]
_## I followed all Prerequisites. But when go for data preprocessing i got this error. Please help me_

--- Step 2: detect landmarks ---
Traceback (most recent call last):
  File "data_util/process_data.py", line 110, in <module>
    tmp_img = cv2.imread(os.path.join(ori_imgs_dir, str(valid_img_ids[0])+'.jpg'))
IndexError: list index out of range
Traceback (most recent call last):
  File "data_util/process_data.py", line 110, in <module>
    tmp_img = cv2.imread(os.path.join(ori_imgs_dir, str(valid_img_ids[0])+'.jpg'))
IndexError: list index out of range
File "data_util/process_data.py", line 110, in <module>
    tmp_img = cv2.imread(os.path.join(ori_imgs_dir, str(valid_img_ids[0])+'.jpg'))
IndexError: list index out of range

**Comment by YudongGuo** [comment]
Hi, I have updated the part and it should be ok now.

**Comment by shahriarshakil0** [comment]
_## Thanks a lot. Step 2 is sloved but I face a different problem in step 6. Can you please help me ?_
--- Step 6: Save Transform Param ---
Traceback (most recent call last):
  File "data_util/process_data.py", line 193, in <module>
    params_dict = torch.load(os.path.join(id_dir, 'track_params.pt'))
  File "/home/mshakil-ecl/anaconda3/envs/adnerf/lib/python3.7/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/mshakil-ecl/anaconda3/envs/adnerf/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/mshakil-ecl/anaconda3/envs/adnerf/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/Obama/track_params.pt'

**Comment by YudongGuo** [comment]
Hi, the trach_params.pt is generated by 'estimate head pose' step (currently step 6), please make sure the step finished.

**Comment by shahriarshakil0** [comment]
_##Step 6 isn't run. I don't understand why skip it while running. But in Step 3 I face this error_

processed parsing 2900
2.074786901473999 -8.417959213256836
Traceback (most recent call last):
  File "data_util/face_tracking/face_tracker.py", line 218, in <module>
    sel_light.to(device_render))
  File "/home/mshakil-ecl/anaconda3/envs/adnerf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mshakil-ecl/AD-NeRF-master/data_util/face_tracking/render_3dmm.py", line 189, in forward
    rendered_img = self.renderer(mesh)
  File "/home/mshakil-ecl/anaconda3/envs/adnerf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mshakil-ecl/AD-NeRF-master/pytorch3d/pytorch3d/renderer/mesh/renderer.py", line 59, in forward
    fragments = self.rasterizer(meshes_world, **kwargs)
  File "/home/mshakil-ecl/anaconda3/envs/adnerf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mshakil-ecl/AD-NeRF-master/pytorch3d/pytorch3d/renderer/mesh/rasterizer.py", line 179, in forward
    cull_to_frustum=raster_settings.cull_to_frustum,
  File "/home/mshakil-ecl/AD-NeRF-master/pytorch3d/pytorch3d/renderer/mesh/rasterize_meshes.py", line 243, in rasterize_meshes
    cull_backfaces,
  File "/home/mshakil-ecl/AD-NeRF-master/pytorch3d/pytorch3d/renderer/mesh/rasterize_meshes.py", line 317, in forward
    cull_backfaces,
RuntimeError: Not compiled with GPU support
processed parsing 3000
processed parsing 3100

**Comment by YudongGuo** [comment]
Actually it was Step 6 output. From the output, pytorch3d was not compiled with GPU support.
