### ISSUE TITLE
step 6 in data preapare

### ISSUE THREAD

**Issue by Liujingxiu23** [YudongGuo/AD-NeRF#35]
--- Estimate Head Pose ---
600 2.0984575748443604 -3.9449377059936523
700 2.07585072517395 -4.621486663818359
800 2.0680198669433594 -5.326531410217285
900 2.0562641620635986 -5.979220867156982
1000 2.0497548580169678 -6.662752628326416
1100 2.046555995941162 -7.34714937210083
1200 2.0465006828308105 -8.076155662536621
1300 2.047314167022705 -8.815178871154785
1400 2.052002191543579 -9.595290184020996
find best focal 1200
2.0739803314208984 -8.418037414550781
Traceback (most recent call last):
  File "data_util/face_tracking/face_tracker.py", line 219, in <module>
    sel_light.to(device_render))
  File "/data/liujingxiu/software/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/liujingxiu/TalkingHead/AD-NeRF-master/data_util/face_tracking/render_3dmm.py", line 189, in forward
    rendered_img = self.renderer(mesh)
TypeError: 'NoneType' object is not callable

what should I do?

**Comment by Liujingxiu23** [comment]
change “return renderer.to(self.device)” to "return renderer" solve the problem.
And pytorch-0.5.0 is ok, pytorch-0.3.0 is not match.
