### ISSUE TITLE
Train Head-NeRF with command OOM

### ISSUE THREAD

**Issue by FieldsYeh** [YudongGuo/AD-NeRF#50]
Hi

When I Trainning AD-NeRF， the Data Preprocess step passed OK, but I have encounter OOM when executing Train Head-NeRF with command, I use RTX2070 8GB GPU card.  should I modify chunk=1024*32 to to avoid OOM, or there are improper  setting in my enviroment. Below are error message:

>  $ python NeRFs/HeadNeRF/run_nerf.py --config dataset/Obama/HeadNeRF_config.txt

```
WARNING: CPU random generator seem to be failing, disabling hardware random number generation
WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff
Loaded audface (7279,) [450, 450, 1200.0, 225.0, 225.0] /mnt/data/hz/test/NeRF/dataset/Obama
Found ckpts []
Not ndc!
N_rand 2048 no_batching True sample_rate 0.95
Begin
TRAIN views are [   0    1    2 ... 7269 7270 7271]
VAL views are [7272 7273 7274 7275 7276 7277 7278]
  0%|                                                | 0/400000 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "NeRFs/HeadNeRF/run_nerf.py", line 965, in <module>
    train()
  File "NeRFs/HeadNeRF/run_nerf.py", line 893, in train
    **render_kwargs_train)
  File "NeRFs/HeadNeRF/run_nerf.py", line 106, in render_dynamic_face
    all_ret = batchify_rays(rays, bc_rgb, aud_para, chunk, **kwargs)
  File "NeRFs/HeadNeRF/run_nerf.py", line 58, in batchify_rays
    aud_para, **kwargs)
  File "NeRFs/HeadNeRF/run_nerf.py", line 463, in render_rays
    raw = network_query_fn(pts, viewdirs, aud_para, network_fn)
  File "NeRFs/HeadNeRF/run_nerf.py", line 262, in network_query_fn
    embed_fn=embed_fn, embeddirs_fn=embeddirs_fn, netchunk=args.netchunk)
  File "NeRFs/HeadNeRF/run_nerf.py", line 46, in run_network
    outputs_flat = batchify(fn, netchunk)(embedded)
  File "NeRFs/HeadNeRF/run_nerf.py", line 29, in ret
    return torch.cat([fn(inputs[i:i+chunk]) for i in range(0, inputs.shape[0], chunk)], 0)
  File "NeRFs/HeadNeRF/run_nerf.py", line 29, in <listcomp>
    return torch.cat([fn(inputs[i:i+chunk]) for i in range(0, inputs.shape[0], chunk)], 0)
  File "/home/hztest/test/anaconda3/envs/nerf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/data/hz/test/NeRF/NeRFs/HeadNeRF/run_nerf_helpers.py", line 193, in forward
    h = F.relu(h)
  File "/home/hztest/test/anaconda3/envs/nerf/lib/python3.7/site-packages/torch/nn/functional.py", line 1206, in relu
    result = torch.relu(input)
RuntimeError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 7.79 GiB total capacity; 6.65 GiB already allocated; 2.06 MiB free; 6.68 GiB reserved in total by PyTorch)
```

**Comment by YudongGuo** [comment]
Hi, you should decrease the N_rand and chunk parameters.

**Comment by FieldsYeh** [comment]
Thanks for your quick response, I modified the N_rand from 2048 to 1024. It is OK now.
