### ISSUE TITLE
Load Pretrained Model

### ISSUE THREAD

**Issue by xinwen-cs** [YudongGuo/AD-NeRF#60]
Hi,
when I run this command to load pretrained model for testing.
```python NeRFs/TorsoNeRF/run_nerf.py --config dataset/Obama/TorsoNeRFTest_config.txt --aud_file=dataset/Obama/aud.npy --test_size=300 --ft_path ./pretrained_models/600000_body.tar```

It outputs 
```Traceback (most recent call last):
File "NeRFs/TorsoNeRF/run_nerf.py", line 1136, in <module>
    train()
File "NeRFs/TorsoNeRF/run_nerf.py", line 754, in train
    args, 'head.tar', args.dim_aud, device, True)
File "NeRFs/TorsoNeRF/run_nerf.py", line 357, in create_nerf
    model.load_state_dict(ckpt['network_fn_state_dict'])
File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1224, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for FaceNeRF:
	size mismatch for pts_linears.0.weight: copying a param with shape torch.Size([256, 169]) from checkpoint, the shape in current model is torch.Size([256, 127]).
	size mismatch for pts_linears.5.weight: copying a param with shape torch.Size([256, 425]) from checkpoint, the shape in current model is torch.Size([256, 383]).
```

Same as #42 
Could you plz help me figure it out?

**Comment by YudongGuo** [comment]
Please refer to #59
